CREATE DATABASE GUITARRA;
USE  GUITARRA;

CREATE TABLE usuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    GUITARRA VARCHAR(100) NOT NULL,
	 MARCA VARCHAR(100) NOT NULL,
     MODELO VARCHAR(100) NOT NULL,
    AÑO VARCHAR(100) NOT NULL,
    DISEÑO VARCHAR(100) NOT NULL,
    COLOR VARCHAR(100) NOT NULL,
    ESTILO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);


select * from usuario;